name: Build GL-MT300N-V2 Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            asciidoc \
            bash \
            bc \
            binutils \
            bzip2 \
            fastjar \
            flex \
            gawk \
            gcc \
            genisoimage \
            gettext \
            git \
            intltool \
            jikespg \
            libgtk2.0-dev \
            libncurses5-dev \
            libssl1.0-dev \
            make \
            mercurial \
            patch \
            perl-modules \
            python2.7-dev \
            rsync \
            ruby \
            sdcc \
            subversion \
            unzip \
            util-linux \
            wget \
            xsltproc \
            zlib1g-dev

      - name: Get SDK and setup feeds
        run: |
          git clone https://github.com/gl-inet/sdk.git
          cd sdk
          ./download.sh ramips-1907
          
          cd 1907/ramips
          echo "src-git modemfeed https://github.com/koshev-msk/modemfeed.git" >> feeds.conf
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Compile modemfeed packages
        working-directory: sdk/1907/ramips
        run: |
          make package/feeds/modemfeed/xmm-modem/compile V=s
          make package/feeds/modemfeed/luci-proto-xmm/compile V=s
          make package/feeds/modemfeed/modeminfo/compile V=s
          make package/feeds/modemfeed/modeminfo-serial-fibocom/compile V=s
          make package/feeds/modemfeed/modeminfo-serial-xmm/compile V=s
          make package/feeds/modemfeed/luci-app-modeminfo/compile V=s
          make package/feeds/modemfeed/luci-i18n-modeminfo-ru/compile V=s
          make package/feeds/modemfeed/atinout/compile V=s
          make package/feeds/modemfeed/luci-app-atinout/compile V=s
          make package/feeds/modemfeed/luci-i18n-atinout-ru/compile V=s

      - name: Upload compiled packages
        uses: actions/upload-artifact@v4
        with:
          name: modem-packages
          path: sdk/1907/ramips/bin/packages/*/modemfeed/*
          retention-days: 5

      - name: Clone imagebuilder
        run: |
          git clone https://github.com/gl-inet/imagebuilder-lede-ramips.git
          cd imagebuilder-lede-ramips
          git clone https://github.com/gl-inet/openwrt-files.git files
          
          # Copy compiled packages
          mkdir -p packages
          cp -r ../sdk/1907/ramips/bin/packages/*/modemfeed/* packages/

      - name: Build firmware
        working-directory: imagebuilder-lede-ramips
        run: |
          make image PROFILE=gl-mt300n-v2 \
          PACKAGES="kmod-mt7628 uci2dat mtk-iwinfo luci \
          kmod-usb-net-cdc-mbim \
          xmm-modem \
          luci-proto-xmm \
          modeminfo \
          modeminfo-serial-fibocom \
          modeminfo-serial-xmm \
          luci-app-modeminfo \
          luci-i18n-modeminfo-ru \
          atinout \
          luci-app-atinout \
          luci-i18n-atinout-ru \
          kmod-usb-acm" \
          FILES=files/files-clean-mt7628/

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: gl-mt300n-v2-firmware
          path: imagebuilder-lede-ramips/bin/targets/ramips/mt76x8/*sysupgrade.bin
          retention-days: 5